apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: infrack
  name: infrack-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infrack
  strategy: {}
  template:
    metadata:
      labels:
        app: infrack
    spec:
      containers:
      - image: bproenca/infrack:s3j17azul
        name: infrack
        resources: 
          requests:
            memory: 128Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 500m
        env:
          - name: JAVA_OPTS
            value: -Xms50M -Xmx100M -XX:+ExitOnOutOfMemoryError
            #value: -Xms50M -Xmx100M
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: infrack
  name: infrack-service
spec:
  ports:
  - name: infrack-port
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: infrack
  type: ClusterIP
status:
  loadBalancer: {}
